name:  Audit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Rust Audit Check
        uses: actions-rs/audit-check@v1.2.0
        with:
          args: "--deny warnings --deny unmaintained --deny unsound"
